services:
  pgsql:
    image: 'postgres:17'
    ports: ['5432:5432']
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE:-casaalba}'
      POSTGRES_USER: '${DB_USERNAME:-casaalba}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'pgsql:/var/lib/postgresql/data'
    healthcheck:
      test: [ CMD, pg_isready, '-q', '-d', '${DB_DATABASE:-casaalba}', '-U', '${DB_USERNAME:-casaalba}' ]
      retries: 3
      timeout: 5s
  mailpit:
      image: 'axllent/mailpit:latest'
      ports:
          - '${FORWARD_MAILPIT_PORT:-1025}:1025'
          - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
volumes:
  pgsql:
    driver: local
